services:
  - type: web
    name: raffle-app
    env: python
    buildCommand: |
      chmod +x build.sh
      ./build.sh
      pip install -r requirements.txt
    startCommand: gunicorn app:app
    envVars:
      - key: PYTHON_VERSION
        value: 3.9.0