# Simulated daily request to your render project so that the service doesn't go down
name: Min render ping

on:
  schedule:
    - cron: '*/10 * * * *'  # Runs daily at midnight UTC
  workflow_dispatch:  # Allows manual triggering

jobs:
  curl-website:
    runs-on: ubuntu-latest

    steps:
      - name: Run cURL on Website
        run: curl -I https://raffle-pwa.onrender.com
